- name: Swap off
  command: swapoff -a

- name: Remove Swap entry from /etc/fstab
  lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: Enable kernel modules 
  command: "{{ item }}"
  with_items: 
    - modprobe overlay
    - modprobe br_netfilter

- name: Configure Persistent loading of moduels
  copy: 
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
- name: Enable kernel moduels
  command: "{{ item }}"
  with_items:
    - modprobe overlay
    - modprobe br_netfilter

- name: Enable Bridging Add sysctl settings
  copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ipv6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward =1 

- name: Apply sysctl changes 
  command: sysctl --system   
  
