- name: open firewall for master nodes
  firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    immediate: true
    permanent: true
  with_items: 
    - 6443
    - 7946
    - 2379-2380
    - 10250
    - 10251
    - 10252


- name: start kubelet service
  systemd: 
    name: kubelet
    state: started
    enabled: true
- name: pull container images
  shell: kubeadm config images pull >> image_pull_out.txt 
  args: 
    chdir: $HOME
    creates: image_pull_out.txt 
- name: Initialize first control node 
  shell: kubeadm init --pod-network-cidr={{ pod_network }} --upload-certs --control-plane-endpoint={{ ctrl_plane_ep }} >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt
  
- name: create .kube directory
  become: true
  become_user: prabhat
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/prabhat/.kube/config
    remote_src: yes
    owner: prabhat

- name: install pod pod_network 
  become: true
  become_user: prabhat
  shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
      chdir: $HOME
      creates: pod_network_setup.txt

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}" 
